import type { Contact, Interaction } from "./types";

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

const now = new Date().toISOString();

// 10 sample NuKava contacts so the app feels alive on first run.
export const SEED_CONTACTS: Contact[] = [
  {
    id: "c1",
    name: "Maya Reyes",
    phone: "801-555-0142",
    email: "maya@mayawellness.co",
    instagram: "@maya.wellness",
    tiktok: "@mayawellness",
    city: "Salt Lake City",
    state: "UT",
    contact_type: "Creator",
    relationship_strength: "Warm",
    lead_temperature: "Hot",
    status: "Approved for Bottles",
    source: "DM on Instagram",
    follower_count: 84000,
    audience_type: "Wellness / fitness",
    owner: "Taylor",
    notes: "Loves adaptogens. Wants to feature NuKava in a morning routine reel.",
    last_contacted_date: daysFromNow(-3),
    next_follow_up_date: daysFromNow(-1),
    bottle_recipient: true,
    bottle_priority: "VIP",
    bottle_status: "Ready to send",
    bottle_quantity: 2,
    shipping_name: "Maya Reyes",
    shipping_address: "245 E 300 S, Salt Lake City, UT 84111",
    tracking_number: "",
    date_sent: null,
    date_delivered: null,
    posted_content: false,
    ambassador_signup: false,
    discount_code: "MAYA15",
    sales_generated: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c2",
    name: "Devin Carter",
    phone: "385-555-0199",
    email: "devin.carter@gmail.com",
    instagram: "@devinlifts",
    tiktok: "@devinlifts",
    city: "Provo",
    state: "UT",
    contact_type: "Ambassador",
    relationship_strength: "Hot",
    lead_temperature: "Hot",
    status: "Ambassador Signed Up",
    source: "Gym event",
    follower_count: 22000,
    audience_type: "Strength training",
    owner: "Taylor",
    notes: "Signed ambassador agreement. Posts consistently.",
    last_contacted_date: daysFromNow(-7),
    next_follow_up_date: daysFromNow(5),
    bottle_recipient: true,
    bottle_priority: "High",
    bottle_status: "Delivered",
    bottle_quantity: 3,
    shipping_name: "Devin Carter",
    shipping_address: "88 N University Ave, Provo, UT 84601",
    tracking_number: "1Z999AA10123456784",
    date_sent: daysFromNow(-14),
    date_delivered: daysFromNow(-11),
    posted_content: true,
    ambassador_signup: true,
    discount_code: "DEVIN10",
    sales_generated: 640,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c3",
    name: "Sofia Lin",
    phone: "",
    email: "sofia@brightreach.agency",
    instagram: "@brightreach",
    tiktok: "",
    city: "Los Angeles",
    state: "CA",
    contact_type: "Agency",
    relationship_strength: "Warm",
    lead_temperature: "Warm",
    status: "Interested",
    source: "Referral from Devin",
    follower_count: null,
    audience_type: "Creator agency (30+ creators)",
    owner: "Taylor",
    notes: "Reps several wellness creators. Wants a wholesale + seeding deal.",
    last_contacted_date: daysFromNow(-2),
    next_follow_up_date: daysFromNow(2),
    bottle_recipient: true,
    bottle_priority: "High",
    bottle_status: "Need address",
    bottle_quantity: 6,
    shipping_name: "",
    shipping_address: "",
    tracking_number: "",
    date_sent: null,
    date_delivered: null,
    posted_content: false,
    ambassador_signup: false,
    discount_code: "",
    sales_generated: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c4",
    name: "Jordan Webb",
    phone: "801-555-0177",
    email: "jordan@webb.com",
    instagram: "@jordaneats",
    tiktok: "@jordaneats",
    city: "Lehi",
    state: "UT",
    contact_type: "Creator",
    relationship_strength: "Cold",
    lead_temperature: "Warm",
    status: "Contacted",
    source: "Found on TikTok",
    follower_count: 156000,
    audience_type: "Food / lifestyle",
    owner: "Taylor",
    notes: "Big TikTok reach. Replied to first DM, asked for more info.",
    last_contacted_date: daysFromNow(-1),
    next_follow_up_date: daysFromNow(1),
    bottle_recipient: true,
    bottle_priority: "Medium",
    bottle_status: "Want to send",
    bottle_quantity: 1,
    shipping_name: "",
    shipping_address: "",
    tracking_number: "",
    date_sent: null,
    date_delivered: null,
    posted_content: false,
    ambassador_signup: false,
    discount_code: "",
    sales_generated: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c5",
    name: "Priya Nair",
    phone: "212-555-0143",
    email: "priya@calmcollective.co",
    instagram: "@calm.priya",
    tiktok: "@calmpriya",
    city: "New York",
    state: "NY",
    contact_type: "Creator",
    relationship_strength: "Warm",
    lead_temperature: "Hot",
    status: "Posted Content",
    source: "Event — Wellness Expo",
    follower_count: 47000,
    audience_type: "Mindfulness / mental health",
    owner: "Taylor",
    notes: "Posted an unboxing story that converted well. Great fit for ongoing.",
    last_contacted_date: daysFromNow(-9),
    next_follow_up_date: daysFromNow(-2),
    bottle_recipient: true,
    bottle_priority: "High",
    bottle_status: "Followed up",
    bottle_quantity: 2,
    shipping_name: "Priya Nair",
    shipping_address: "120 W 21st St, New York, NY 10011",
    tracking_number: "9400111899560000000000",
    date_sent: daysFromNow(-20),
    date_delivered: daysFromNow(-16),
    posted_content: true,
    ambassador_signup: false,
    discount_code: "PRIYA15",
    sales_generated: 310,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c6",
    name: "Coastal Health Market",
    phone: "619-555-0188",
    email: "buyer@coastalhealth.com",
    instagram: "@coastalhealthmkt",
    tiktok: "",
    city: "San Diego",
    state: "CA",
    contact_type: "Retailer",
    relationship_strength: "Cold",
    lead_temperature: "Warm",
    status: "New Lead",
    source: "Cold outreach",
    follower_count: null,
    audience_type: "Local health food retail",
    owner: "Taylor",
    notes: "Independent health market. Open to a wholesale sample order.",
    last_contacted_date: null,
    next_follow_up_date: daysFromNow(0),
    bottle_recipient: true,
    bottle_priority: "Medium",
    bottle_status: "Want to send",
    bottle_quantity: 4,
    shipping_name: "Coastal Health Market",
    shipping_address: "1500 Garnet Ave, San Diego, CA 92109",
    tracking_number: "",
    date_sent: null,
    date_delivered: null,
    posted_content: false,
    ambassador_signup: false,
    discount_code: "",
    sales_generated: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c7",
    name: "Alex Tanaka",
    phone: "801-555-0121",
    email: "alex.tanaka@gmail.com",
    instagram: "@alexoutdoors",
    tiktok: "@alexoutdoors",
    city: "Park City",
    state: "UT",
    contact_type: "Friend",
    relationship_strength: "Close Friend",
    lead_temperature: "Hot",
    status: "Bottle Sent",
    source: "Personal friend",
    follower_count: 9000,
    audience_type: "Outdoor / adventure",
    owner: "Taylor",
    notes: "Friend who genuinely loves the product. Will refer others.",
    last_contacted_date: daysFromNow(-5),
    next_follow_up_date: daysFromNow(3),
    bottle_recipient: true,
    bottle_priority: "Medium",
    bottle_status: "Sent",
    bottle_quantity: 2,
    shipping_name: "Alex Tanaka",
    shipping_address: "55 Main St, Park City, UT 84060",
    tracking_number: "1Z999AA10123456111",
    date_sent: daysFromNow(-2),
    date_delivered: null,
    posted_content: false,
    ambassador_signup: false,
    discount_code: "ALEX10",
    sales_generated: 120,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c8",
    name: "Bianca Ortiz",
    phone: "305-555-0166",
    email: "bianca@miamiglow.co",
    instagram: "@miamiglow",
    tiktok: "@miamiglow",
    city: "Miami",
    state: "FL",
    contact_type: "Creator",
    relationship_strength: "Warm",
    lead_temperature: "Warm",
    status: "Needs Follow-Up",
    source: "Instagram comment",
    follower_count: 63000,
    audience_type: "Beauty / wellness",
    owner: "Taylor",
    notes: "Interested but went quiet. Needs a nudge with a sample offer.",
    last_contacted_date: daysFromNow(-12),
    next_follow_up_date: daysFromNow(-4),
    bottle_recipient: true,
    bottle_priority: "Medium",
    bottle_status: "Need address",
    bottle_quantity: 1,
    shipping_name: "",
    shipping_address: "",
    tracking_number: "",
    date_sent: null,
    date_delivered: null,
    posted_content: false,
    ambassador_signup: false,
    discount_code: "",
    sales_generated: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c9",
    name: "Greenleaf Distributors",
    phone: "503-555-0150",
    email: "orders@greenleafdist.com",
    instagram: "",
    tiktok: "",
    city: "Portland",
    state: "OR",
    contact_type: "Wholesale",
    relationship_strength: "Cold",
    lead_temperature: "Cold",
    status: "New Lead",
    source: "Trade show",
    follower_count: null,
    audience_type: "Regional distributor",
    owner: "Taylor",
    notes: "Distributes to 40+ stores in the PNW. Requested wholesale pricing.",
    last_contacted_date: null,
    next_follow_up_date: daysFromNow(4),
    bottle_recipient: false,
    bottle_priority: "Low",
    bottle_status: "Not planned",
    bottle_quantity: null,
    shipping_name: "",
    shipping_address: "",
    tracking_number: "",
    date_sent: null,
    date_delivered: null,
    posted_content: false,
    ambassador_signup: false,
    discount_code: "",
    sales_generated: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "c10",
    name: "Tyler Brooks",
    phone: "801-555-0133",
    email: "tyler.brooks@gmail.com",
    instagram: "@tylerbrooksfit",
    tiktok: "@tylerbrooksfit",
    city: "Ogden",
    state: "UT",
    contact_type: "Event Contact",
    relationship_strength: "Warm",
    lead_temperature: "Warm",
    status: "Interested",
    source: "Met at NuKava pop-up",
    follower_count: 14000,
    audience_type: "Fitness / supplements",
    owner: "Taylor",
    notes: "Grabbed a sample at the booth, texted that he loved it.",
    last_contacted_date: daysFromNow(-1),
    next_follow_up_date: daysFromNow(2),
    bottle_recipient: true,
    bottle_priority: "Medium",
    bottle_status: "Ready to send",
    bottle_quantity: 1,
    shipping_name: "Tyler Brooks",
    shipping_address: "390 Washington Blvd, Ogden, UT 84401",
    tracking_number: "",
    date_sent: null,
    date_delivered: null,
    posted_content: false,
    ambassador_signup: false,
    discount_code: "",
    sales_generated: 0,
    created_at: now,
    updated_at: now,
  },
];

export const SEED_INTERACTIONS: Interaction[] = [
  {
    id: "i1",
    contact_id: "c1",
    date: daysFromNow(-3),
    type: "DM'd",
    notes: "She asked for ingredient list and pricing. Sent over deck.",
    next_action: "Ship VIP bottles once address confirmed.",
    created_at: now,
  },
  {
    id: "i2",
    contact_id: "c2",
    date: daysFromNow(-14),
    type: "Sent bottle",
    notes: "Shipped 3 bottles for his ambassador kit.",
    next_action: "Check in after first post.",
    created_at: now,
  },
  {
    id: "i3",
    contact_id: "c2",
    date: daysFromNow(-7),
    type: "Posted content",
    notes: "Posted a pre-workout reel — strong engagement.",
    next_action: "Send next month's restock.",
    created_at: now,
  },
  {
    id: "i4",
    contact_id: "c5",
    date: daysFromNow(-2),
    type: "Followed up",
    notes: "Thanked her for the unboxing story. Discussed ongoing partnership.",
    next_action: "Propose monthly content cadence.",
    created_at: now,
  },
  {
    id: "i5",
    contact_id: "c7",
    date: daysFromNow(-2),
    type: "Sent bottle",
    notes: "Dropped off 2 bottles personally.",
    next_action: "Ask him to tag a friend.",
    created_at: now,
  },
];
